{% set name = "cnmaps" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Clarmy/cnmaps/archive/refs/tags/{{ version }}.tar.gz
  sha256: 209f9de72dfb6111684a7ecff572d89b4d3f88fb57fae5d555a59f3e7378c1a6

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.8
    - pip
    - poetry
  run:
    - python >=3.8
    - matplotlib-base
    - Cartopy >=0.20.0
    - Shapely >=1.8.0,<2.0
    - numpy
    - netCDF4
    - geopandas
    - Fiona
    - geojson
    - orjson
    - numba

test:
  imports:
    - cnmaps
  requires:
    - pip
  commands:
    - pip list

about:
  home: https://github.com/Clarmy/cnmaps
  summary: 'cnmaps is a python package that make drawing China maps more easily. '
  description: |
    cnmaps is a python package that make drawing China maps more easily. 
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/Clarmy/cnmaps

extra:
  recipe-maintainers:
    - Clarmy
