{% set name = "cnmaps" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Clarmy/cnmaps/archive/refs/tags/{{ version }}.tar.gz
  sha256: 7d8b065a3507e29761afff12d7cd324eb429310cc5400950d9b4e8084207637c

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - matplotlib-base
    - Cartopy >=0.20.0
    - Shapely
    - numpy
    - netCDF4
    - geopandas
    - Fiona
    - geojson
    - orjson
    - numba

test:
  imports:
    - cnmaps
  requires:
    - pip
  commands:
    - pip list

about:
  home: https://github.com/Clarmy/cnmaps
  summary: 'cnmaps is a python package that make drawing China maps more easily. '
  description: |
    cnmaps is a python package that make drawing China maps more easily. 
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/Clarmy/cnmaps

extra:
  recipe-maintainers:
    - Clarmy
