{% set name = "cnmaps" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Clarmy/cnmaps/archive/refs/tags/{{ version }}.tar.gz
  sha256: 5f3a776ce2d156949eb3f880eea30411d9938be2bcffaa2e8523cc6343477669

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - matplotlib-base
    - Cartopy >=0.19.0
    - Shapely
    - numpy
    - netCDF4
    - geopandas
    - Fiona
    - geojson

test:
  imports:
    - cnmaps
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/Clarmy/cnmaps
  summary: 'cnmaps is a python package that make drawing China maps more easily. '
  description: |
    cnmaps is a python package that make drawing China maps more easily. 
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/Clarmy/cnmaps

extra:
  recipe-maintainers:
    - Clarmy
