{% set name = "cnmaps" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Clarmy/cnmaps/archive/refs/tags/{{ version }}.tar.gz
  sha256: 33233e20ead81fd2f3f86dbc6b4efa26d6cf131c9eb451da2014ec88ab4cb2f6

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - matplotlib-base
    - Cartopy >=0.20.0
    - Shapely
    - numpy
    - netCDF4
    - geopandas
    - Fiona
    - geojson
    - numba >=0.56.0
    - orjson

test:
  imports:
    - cnmaps
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/Clarmy/cnmaps
  summary: 'cnmaps is a python package that make drawing China maps more easily. '
  description: |
    cnmaps is a python package that make drawing China maps more easily. 
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/Clarmy/cnmaps

extra:
  recipe-maintainers:
    - Clarmy
